=== aadarshasubedi/GameBookAndroid/assets/template/story.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="story" type="storyType" />
	<xs:complexType name="characterType">
		<xs:sequence>
			<xs:element type="xs:int" name="health" />
			<xs:element type="xs:int" name="defense" />
			<xs:element type="xs:int" name="skill" />
			<xs:element type="xs:int" name="luck" />
		</xs:sequence>
		<xs:attribute type="xs:int" name="position" use="required">
			<xs:annotation>
				<xs:documentation>Start section position of character
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:int" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required">
			<xs:annotation>
				<xs:documentation>Name of character</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="description" use="required">
			<xs:annotation>
				<xs:documentation>Description of character</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="charactersType">
		<xs:sequence>
			<xs:element type="characterType" name="character" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="bonusType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="type" use="optional" />
				<xs:attribute type="xs:int" name="value" use="optional" />
				<xs:attribute type="xs:string" name="debuff" use="optional" />
				<xs:attribute type="xs:string" name="state" use="optional" />
				<xs:attribute type="xs:string" name="overflowed" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="bonusesType">
		<xs:sequence>
			<xs:element type="bonusType" name="bonus" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="enemyType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="attack" use="required" />
				<xs:attribute type="xs:int" name="skill" use="required" />
				<xs:attribute type="xs:string" name="name" use="required" />
				<xs:attribute type="xs:string" name="fightWithoutDamageText"
					use="optional">
					<xs:annotation>
						<xs:documentation>Text will shown when character's health is not
							affected by enemy. Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="fightWithDamageText"
					use="optional">
					<xs:annotation>
						<xs:documentation>Text will shown when character's health is
							affected by enemy. Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="fightSkillText"
					use="optional">
					<xs:annotation>
						<xs:documentation>Text will shown when character's skill is
							greater then enemy skill. Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="fightLoseText"
					use="optional">
					<xs:annotation>
						<xs:documentation>Text will shown when character is defeated by
							enemy. Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="fightLuckText"
					use="optional">
					<xs:annotation>
						<xs:documentation>Text will shown when character has luck in fight
							with enemy. Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="enemiesType">
		<xs:sequence>
			<xs:element type="enemyType" name="enemy" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="optionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="section" use="required">
					<xs:annotation>
						<xs:documentation>Position of next section.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="text" use="required">
					<xs:annotation>
						<xs:documentation>Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="optionsType">
		<xs:sequence>
			<xs:element type="optionType" name="option" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sectionType" mixed="true">
		<xs:sequence>
			<xs:element type="bonusesType" name="bonuses" minOccurs="0" />
			<xs:element type="enemiesType" name="enemies" minOccurs="0" />
			<xs:element type="optionsType" name="options" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:int" name="position" use="required" />
		<xs:attribute type="xs:string" name="text" use="required">
			<xs:annotation>
				<xs:documentation>Part of text of story. Text is android string reference and must have format "@string/text".</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="enemiesDefeatedText"
			use="optional">
			<xs:annotation>
				<xs:documentation>Text will shown when player defeated all enemies
					(this is required when enemies are defined). Text is android string reference and must have format "@string/text".</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="luckText" use="optional">
			<xs:annotation>
				<xs:documentation>Text will shown when player has luck and avoid
					combat. Text is android string reference and must have format "@string/text".</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="endGame" use="optional">
			<xs:annotation>
				<xs:documentation>Indicates this is end of game (last section).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="sectionsType">
		<xs:sequence>
			<xs:element type="sectionType" name="section" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Section of story</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="storyType">
		<xs:sequence>
			<xs:element type="charactersType" name="characters" />
			<xs:element type="sectionsType" name="sections" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required">
			<xs:annotation>
				<xs:documentation>Text is android string reference and must have format "@string/text".</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== aadarshasubedi/GameBookAndroid/assets/story1.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/E:/develop/git/GameBook/assets/story.xsd"
	name="@string/story_zombie_apocalypse">

   	<characters>
   	    <character position="3" id="1" name="@string/s1_ch_soldier" description="@string/s1_dsc_soldier">
   	        <health>3</health>
   	        <defense>4</defense>
   	        <skill>2</skill>
   	        <luck>2</luck>
   	    </character>
   	    <character position="4" id="2" name="@string/s1_ch_homeless" description="@string/s1_dsc_homeless">
   	        <health>20</health>
   	        <defense>2</defense>
   	        <skill>4</skill>
   	        <luck>2</luck>
   	    </character>
   	</characters>
   	
	<sections>
	    <section position="1" text="@string/s1_section1">
	        <options>
	            <option section="2" text="@string/s1_section1_option1" skill="2" />
	            <option section="2" text="@string/s1_section1_option2" />
	        </options>
	    </section>
	
	    <section position="2" text="@string/s1_section2_endGame" endgame="true" />
	    
	    <section position="3" text="@string/s1_section3" enemiesDefeatedText="@string/s1_section3_cleared" luckText="@string/fight_luck_section">
	        <bonuses>
	            <bonus type="defense" value="1" debuff="true" state="before_fight" />
	            <bonus type="luck" value="3" overflowed="true" state="after_fight" />
	        </bonuses>
	        <enemies>
	            <enemy attack="4" skill="5" name="@string/s1_enemy_zombie" />
	            <enemy attack="2" skill="4" name="@string/s1_enemy_zombie" />
	            <enemy attack="6" skill="2" name="@string/s1_enemy_zombie" />
	            <enemy attack="6" skill="2" name="@string/s1_enemy_zombie" />
	        </enemies>
	        <options>
	            <option section="2" text="@string/sg_continue"/>
	        </options>
	    </section>
	    
	    <section position="4" text="@string/s1_section2">
	        <bonuses>
	            <bonus type="health" value="20" debuff="true" overflowed="true" />
	            <bonus type="luck" value="1" debuff="true"/>
	        </bonuses>
	        <options>
	            <option section="1" text="@string/sg_continue"/>
	        </options>
	    </section>
    </sections>
</story>
